Repository woocommerce/woocommerce-rest-api, pull requests merged in 2019-12, with the labels that each got.

#10 Fixed date_created and date_created_gmt for customers v2
  src/Controllers/Version2/class-wc-rest-customers-v2-controller.php
Labels: cherry-pick 🍒, status: ready to merge

#14 filter empty objects from results before loop
  src/Controllers/Version3/class-wc-rest-crud-controller.php
  src/Controllers/Version4/AbstractObjectsController.php
Labels: cherry-pick 🍒, status: ready to merge

#65 Add Renovate
  renovate.json
Labels: status: ready to merge

#29 Update class-wc-rest-system-status-v2-controller.php
  src/Controllers/Version2/class-wc-rest-system-status-v2-controller.php
Labels: cherry-pick 🍒, status: ready to merge

#74 Reintroduced "post_type_counts" in System Status
  src/Controllers/Version2/class-wc-rest-system-status-v2-controller.php
  unit-tests/Tests/Version2/system-status.php
  unit-tests/Tests/Version3/system-status.php
Labels: cherry-pick 🍒, status: ready to merge

#79 Make product_id non mandatory while updating a line_item in orders endpoint
  src/Controllers/Version1/class-wc-rest-orders-v1-controller.php
  src/Controllers/Version2/class-wc-rest-orders-v2-controller.php
  unit-tests/Tests/Version2/orders.php
  unit-tests/Tests/Version3/orders.php
Labels: status: needs review

#82 Added support for filtering products and variations by their menu_order
  src/Controllers/Version2/class-wc-rest-products-v2-controller.php
  unit-tests/Tests/Version2/product-variations.php
  unit-tests/Tests/Version3/product-variations.php
Labels: status: ready to merge

#88 Test the correct orders endpoint
  unit-tests/Tests/Version3/orders.php
Labels: status: needs review

#87 [v4] Make product_id non mandatory while updating a line_item in orders endpoint
  src/Controllers/Version4/Requests/OrderRequest.php
  unit-tests/Tests/Version4/Orders.php
Labels: status: needs review

#86 [v4] Fixed Product's images schema type
  src/Controllers/Version4/Products.php
Labels: status: needs review

#84 Fixed type numeric type on products and variations schema
  src/Controllers/Version3/class-wc-rest-product-variations-controller.php
  src/Controllers/Version3/class-wc-rest-products-controller.php
  src/Controllers/Version4/ProductVariations.php
  src/Controllers/Version4/Products.php
Labels: status: needs review
