Repository woocommerce/woocommerce-rest-api, pull requests merged in 2020-07, with the labels that each got.

#152 Clear Action Scheduler Transients
  src/Controllers/Version2/class-wc-rest-system-status-tools-v2-controller.php
Labels: status: approved

#163 Update jetpack autoloader to ^1.6
  composer.json
  composer.lock
Labels: status: approved

#171 add X-WP-Total headers to product attribute API calls
  src/Controllers/Version1/class-wc-rest-product-attributes-v1-controller.php
  src/Controllers/Version4/ProductAttributes.php
Labels: status: approved

#176 Fix expiry date fields in coupon schema definitions
  src/Controllers/Version1/class-wc-rest-coupons-v1-controller.php
  src/Controllers/Version2/class-wc-rest-coupons-v2-controller.php
Labels: status: approved

#191 forward query params (product variations)
  src/Controllers/Version2/class-wc-rest-product-variations-v2-controller.php
Labels: needs cherry picking, status: approved

#226 Support `modified` param for `orderby` in post based resources.
  src/Controllers/Version3/class-wc-rest-crud-controller.php
  src/Controllers/Version3/class-wc-rest-posts-controller.php
  unit-tests/Tests/Version3/orders.php
Labels: status: needs review

#225 Fix tests in response to Core 25630
  unit-tests/Tests/Version2/settings.php
  unit-tests/Tests/Version3/settings.php
  unit-tests/Tests/Version4/Settings.php
Labels: status: needs review

#227 Jetpack Autoloader 2.0 Update
  composer.json
  composer.lock
Labels: status: needs review
